"""Generate the bundled, offline emoji name table from iamcal/emoji-data emoji.json.
Usage: python3 scripts/build-emoji-data.py /path/to/emoji.json
Source: https://github.com/iamcal/emoji-data (MIT; see third-party/emoji-data-LICENSE.txt).
"""
import hashlib,json,pathlib,sys
raw=pathlib.Path(sys.argv[1]).read_bytes()
entries=json.loads(raw)
names={}
def unicode(value): return ''.join(chr(int(c,16)) for c in value.split('-'))
def put(name,value):
    key=':'+name+':'
    if key in names and names[key]!=value: raise ValueError('Ambiguous alias: '+key)
    names[key]=value
for entry in entries:
    aliases=set(entry['short_names'])
    for name in list(aliases):
        if name.startswith('flag-'): aliases.add(name.replace('flag-','flag_',1))
    for name in aliases:
        put(name,unicode(entry['unified']))
        for tones,variant in entry.get('skin_variations',{}).items():
            numbers=[int(t,16)-0x1f3fb+2 for t in tones.split('-')]
            suffix=':'.join(':skin-tone-'+str(n) for n in numbers)
            put(name+':'+suffix,unicode(variant['unified']))
            if len(numbers)==1: put(name+'_tone'+str(numbers[0]),unicode(variant['unified']))
body='// Generated by scripts/build-emoji-data.py; do not edit by hand.\n'
body+='// Source: iamcal/emoji-data emoji.json; SHA256 '+hashlib.sha256(raw).hexdigest()+'\n'
body+='// MIT Copyright (c) 2013 Cal Henderson; see third-party/emoji-data-LICENSE.txt.\n'
body+='globalThis.__dicoEmojiNames = Object.freeze('+json.dumps(dict(sorted(names.items())),ensure_ascii=False,indent=2)+');\n'
pathlib.Path('emoji-data.js').write_text(body)
print(len(entries),'base entries;',len(names),'aliases')
